// <auto-generated>
namespace Monolito4toA {
    public partial class UserJuego {
        protected global::System.Web.UI.WebControls.Literal litBestScore;
        protected global::System.Web.UI.WebControls.Literal litScoresList;
        protected global::System.Web.UI.WebControls.HiddenField hfScoreSave;
        protected global::System.Web.UI.WebControls.Button btnSaveScoreHidden;
    }
}
