#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Monolillo4to")]
	public partial class DactaClasesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Updatetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Deletetbl_tipo_usuario(tbl_tipo_usuario instance);
    partial void Inserttbl_usuario(tbl_usuario instance);
    partial void Updatetbl_usuario(tbl_usuario instance);
    partial void Deletetbl_usuario(tbl_usuario instance);
    #endregion
		
		public DactaClasesDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.Monolillo4toConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DactaClasesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DactaClasesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DactaClasesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DactaClasesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_tipo_usuario> tbl_tipo_usuario
		{
			get
			{
				return this.GetTable<tbl_tipo_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_usuario> tbl_usuario
		{
			get
			{
				return this.GetTable<tbl_usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_tipo_usuario")]
	public partial class tbl_tipo_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tusu_id;
		
		private string _tusu_nombre;
		
		private System.Nullable<char> _tusu_estado;
		
		private EntitySet<tbl_usuario> _tbl_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontusu_idChanging(int value);
    partial void Ontusu_idChanged();
    partial void Ontusu_nombreChanging(string value);
    partial void Ontusu_nombreChanged();
    partial void Ontusu_estadoChanging(System.Nullable<char> value);
    partial void Ontusu_estadoChanged();
    #endregion
		
		public tbl_tipo_usuario()
		{
			this._tbl_usuario = new EntitySet<tbl_usuario>(new Action<tbl_usuario>(this.attach_tbl_usuario), new Action<tbl_usuario>(this.detach_tbl_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_nombre", DbType="VarChar(50)")]
		public string tusu_nombre
		{
			get
			{
				return this._tusu_nombre;
			}
			set
			{
				if ((this._tusu_nombre != value))
				{
					this.Ontusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._tusu_nombre = value;
					this.SendPropertyChanged("tusu_nombre");
					this.Ontusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_estado", DbType="Char(1)")]
		public System.Nullable<char> tusu_estado
		{
			get
			{
				return this._tusu_estado;
			}
			set
			{
				if ((this._tusu_estado != value))
				{
					this.Ontusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._tusu_estado = value;
					this.SendPropertyChanged("tusu_estado");
					this.Ontusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_usuario", ThisKey="tusu_id", OtherKey="tusu_id")]
		public EntitySet<tbl_usuario> tbl_usuario
		{
			get
			{
				return this._tbl_usuario;
			}
			set
			{
				this._tbl_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = this;
		}
		
		private void detach_tbl_usuario(tbl_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_tipo_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_usuario")]
	public partial class tbl_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_cedula;
		
		private string _usu_nombres;
		
		private string _usu_apellidos;
		
		private string _usu_direcciones;
		
		private string _usu_celular;
		
		private string _usu_correo;
		
		private System.Nullable<System.DateTime> _usu_fecha_creacion;
		
		private System.Nullable<System.DateTime> _usu_fecha_cumple;
		
		private string _usu_nick;
		
		private System.Data.Linq.Binary _usu_contraseña;
		
		private System.Nullable<int> _usu_intentos;
		
		private string _usu_codigo_OTP;
		
		private System.Nullable<char> _usu_estado;
		
		private System.Nullable<int> _tusu_id;
		
		private System.Nullable<System.DateTime> _usu_fecha_ultimo_intento;
		
		private string _usu_imagen;
		
		private string _usu_qr_key;
		
		private EntityRef<tbl_tipo_usuario> _tbl_tipo_usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_nombresChanging(string value);
    partial void Onusu_nombresChanged();
    partial void Onusu_apellidosChanging(string value);
    partial void Onusu_apellidosChanged();
    partial void Onusu_direccionesChanging(string value);
    partial void Onusu_direccionesChanged();
    partial void Onusu_celularChanging(string value);
    partial void Onusu_celularChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_fecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_creacionChanged();
    partial void Onusu_fecha_cumpleChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_cumpleChanged();
    partial void Onusu_nickChanging(string value);
    partial void Onusu_nickChanged();
    partial void Onusu_contraseñaChanging(System.Data.Linq.Binary value);
    partial void Onusu_contraseñaChanged();
    partial void Onusu_intentosChanging(System.Nullable<int> value);
    partial void Onusu_intentosChanged();
    partial void Onusu_codigo_OTPChanging(string value);
    partial void Onusu_codigo_OTPChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Ontusu_idChanging(System.Nullable<int> value);
    partial void Ontusu_idChanged();
    partial void Onusu_fecha_ultimo_intentoChanging(System.Nullable<System.DateTime> value);
    partial void Onusu_fecha_ultimo_intentoChanged();
    partial void Onusu_imagenChanging(string value);
    partial void Onusu_imagenChanged();
    partial void Onusu_qr_keyChanging(string value);
    partial void Onusu_qr_keyChanged();
    #endregion
		
		public tbl_usuario()
		{
			this._tbl_tipo_usuario = default(EntityRef<tbl_tipo_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="VarChar(10)")]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombres", DbType="VarChar(50)")]
		public string usu_nombres
		{
			get
			{
				return this._usu_nombres;
			}
			set
			{
				if ((this._usu_nombres != value))
				{
					this.Onusu_nombresChanging(value);
					this.SendPropertyChanging();
					this._usu_nombres = value;
					this.SendPropertyChanged("usu_nombres");
					this.Onusu_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellidos", DbType="VarChar(50)")]
		public string usu_apellidos
		{
			get
			{
				return this._usu_apellidos;
			}
			set
			{
				if ((this._usu_apellidos != value))
				{
					this.Onusu_apellidosChanging(value);
					this.SendPropertyChanging();
					this._usu_apellidos = value;
					this.SendPropertyChanged("usu_apellidos");
					this.Onusu_apellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_direcciones", DbType="VarChar(50)")]
		public string usu_direcciones
		{
			get
			{
				return this._usu_direcciones;
			}
			set
			{
				if ((this._usu_direcciones != value))
				{
					this.Onusu_direccionesChanging(value);
					this.SendPropertyChanging();
					this._usu_direcciones = value;
					this.SendPropertyChanged("usu_direcciones");
					this.Onusu_direccionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_celular", DbType="VarChar(10)")]
		public string usu_celular
		{
			get
			{
				return this._usu_celular;
			}
			set
			{
				if ((this._usu_celular != value))
				{
					this.Onusu_celularChanging(value);
					this.SendPropertyChanging();
					this._usu_celular = value;
					this.SendPropertyChanged("usu_celular");
					this.Onusu_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(150)")]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_creacion
		{
			get
			{
				return this._usu_fecha_creacion;
			}
			set
			{
				if ((this._usu_fecha_creacion != value))
				{
					this.Onusu_fecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_creacion = value;
					this.SendPropertyChanged("usu_fecha_creacion");
					this.Onusu_fecha_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_cumple", DbType="Date")]
		public System.Nullable<System.DateTime> usu_fecha_cumple
		{
			get
			{
				return this._usu_fecha_cumple;
			}
			set
			{
				if ((this._usu_fecha_cumple != value))
				{
					this.Onusu_fecha_cumpleChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_cumple = value;
					this.SendPropertyChanged("usu_fecha_cumple");
					this.Onusu_fecha_cumpleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nick", DbType="VarChar(50)")]
		public string usu_nick
		{
			get
			{
				return this._usu_nick;
			}
			set
			{
				if ((this._usu_nick != value))
				{
					this.Onusu_nickChanging(value);
					this.SendPropertyChanging();
					this._usu_nick = value;
					this.SendPropertyChanged("usu_nick");
					this.Onusu_nickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contraseña", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary usu_contraseña
		{
			get
			{
				return this._usu_contraseña;
			}
			set
			{
				if ((this._usu_contraseña != value))
				{
					this.Onusu_contraseñaChanging(value);
					this.SendPropertyChanging();
					this._usu_contraseña = value;
					this.SendPropertyChanged("usu_contraseña");
					this.Onusu_contraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_intentos", DbType="Int")]
		public System.Nullable<int> usu_intentos
		{
			get
			{
				return this._usu_intentos;
			}
			set
			{
				if ((this._usu_intentos != value))
				{
					this.Onusu_intentosChanging(value);
					this.SendPropertyChanging();
					this._usu_intentos = value;
					this.SendPropertyChanged("usu_intentos");
					this.Onusu_intentosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_codigo_OTP", DbType="VarChar(10)")]
		public string usu_codigo_OTP
		{
			get
			{
				return this._usu_codigo_OTP;
			}
			set
			{
				if ((this._usu_codigo_OTP != value))
				{
					this.Onusu_codigo_OTPChanging(value);
					this.SendPropertyChanging();
					this._usu_codigo_OTP = value;
					this.SendPropertyChanged("usu_codigo_OTP");
					this.Onusu_codigo_OTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", DbType="Int")]
		public System.Nullable<int> tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					if (this._tbl_tipo_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_fecha_ultimo_intento", DbType="DateTime")]
		public System.Nullable<System.DateTime> usu_fecha_ultimo_intento
		{
			get
			{
				return this._usu_fecha_ultimo_intento;
			}
			set
			{
				if ((this._usu_fecha_ultimo_intento != value))
				{
					this.Onusu_fecha_ultimo_intentoChanging(value);
					this.SendPropertyChanging();
					this._usu_fecha_ultimo_intento = value;
					this.SendPropertyChanged("usu_fecha_ultimo_intento");
					this.Onusu_fecha_ultimo_intentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_imagen", DbType="VarChar(250)")]
		public string usu_imagen
		{
			get
			{
				return this._usu_imagen;
			}
			set
			{
				if ((this._usu_imagen != value))
				{
					this.Onusu_imagenChanging(value);
					this.SendPropertyChanging();
					this._usu_imagen = value;
					this.SendPropertyChanged("usu_imagen");
					this.Onusu_imagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_qr_key", DbType="VarChar(100)")]
		public string usu_qr_key
		{
			get
			{
				return this._usu_qr_key;
			}
			set
			{
				if ((this._usu_qr_key != value))
				{
					this.Onusu_qr_keyChanging(value);
					this.SendPropertyChanging();
					this._usu_qr_key = value;
					this.SendPropertyChanged("usu_qr_key");
					this.Onusu_qr_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_tipo_usuario_tbl_usuario", Storage="_tbl_tipo_usuario", ThisKey="tusu_id", OtherKey="tusu_id", IsForeignKey=true)]
		public tbl_tipo_usuario tbl_tipo_usuario
		{
			get
			{
				return this._tbl_tipo_usuario.Entity;
			}
			set
			{
				tbl_tipo_usuario previousValue = this._tbl_tipo_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tbl_tipo_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_tipo_usuario.Entity = null;
						previousValue.tbl_usuario.Remove(this);
					}
					this._tbl_tipo_usuario.Entity = value;
					if ((value != null))
					{
						value.tbl_usuario.Add(this);
						this._tusu_id = value.tusu_id;
					}
					else
					{
						this._tusu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_tipo_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
