// <auto-generated>
namespace Monolito4toA.Seguridad {
    public partial class Registrar {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.FileUpload fuImagen;
        protected global::System.Web.UI.WebControls.Button btnSubirImagen;
        protected global::System.Web.UI.WebControls.Panel divPreviewsContainer;
        protected global::System.Web.UI.WebControls.Repeater repPreviews;
        protected global::System.Web.UI.WebControls.Label lblUploadStatus;
        protected global::System.Web.UI.WebControls.HiddenField hfSelectedIndex;
        protected global::System.Web.UI.WebControls.TextBox txtCedula;
        protected global::System.Web.UI.WebControls.TextBox txtNick;
        protected global::System.Web.UI.WebControls.TextBox txtNombres;
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;
        protected global::System.Web.UI.WebControls.TextBox txtCelular;
        protected global::System.Web.UI.WebControls.TextBox txtFechaCumple;
        protected global::System.Web.UI.WebControls.TextBox txtDireccion;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
        protected global::System.Web.UI.WebControls.LinkButton btnGoogleRegister;
        protected global::System.Web.UI.WebControls.LinkButton btnGithubRegister;
        protected global::System.Web.UI.WebControls.LinkButton lnkLogin;
    }
}
